language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
 - pip install -r requirements-dev.txt
 - pip install -r requirements.txt

script:
  - flake8 hybrid_crypto/
  - flake8 --max-line-len=250 tests/
  - python setup.py test

notifications:
  email:
    - tomaz+travisci@tomaz.me
